cassandra:
    image: cassandra
    container_name: cassandra
    environment:
        - CASSANDRA_RPC_ADDRESS=127.0.0.1
        - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
        - CASSANDRA_START_RPC=true
    ports:
        - 7000:7000
        - 7001:7001
        - 7199:7199
        - 9042:9042
        - 9160:9160
        - 9200:9200
        - 9300:9300